### ISSUE TITLE
Site is entirely blank in IE11

### ISSUE THREAD

**Issue by dracos** [PublicHealthEngland/coronavirus-dashboard#125]
"Symbol is undefined" is the console error.

![image](https://user-images.githubusercontent.com/154364/80747500-74e89980-8b1b-11ea-8f4a-2c0209eb4d44.png)

**Comment by xenatisch** [comment]
It is in the backlog. Comes from the `pythonic` module. I'll have to write the `zip` function without Symbol. In fact, I already have, I just need to integrate it. It's not a high priority issue as it affects 1.96% of the users, majority of whom usually have access to another browser. 

Hopefully gets fixed by the end of the week.

**Comment by xenatisch** [comment]
The next release will include a fix for this issue.
