### ISSUE TITLE
Missing data for regional breakdown CSV

### ISSUE THREAD

**Issue by robchallen** [PublicHealthEngland/coronavirus-dashboard#153]
The UTLA breakdown of cases is missing data for a number of regions for the 31st April and 1st May. For example hartlepool has no entries for those dates.

https://coronavirus.data.gov.uk/downloads/csv/coronavirus-cases_latest.csv

**Comment by xenatisch** [comment]
@przemyslawpluta I'm afraid the main answer is the same as #154 - this is not a development issue. 

Missing areas in the CSV means that the value has remain unchanged since the preceding report.

Please read the [About the data](https://coronavirus.data.gov.uk/about) section of the website where the reason for these inconsistencies are explained.

For additional questions and requests, please get in touch using the email provided in the footer of the website.
