### ISSUE TITLE
coronavirus-cases_latest.json seems to be malformed and not compressed

### ISSUE THREAD

**Issue by przemyslawpluta** [PublicHealthEngland/coronavirus-dashboard#170]
After requesting **coronavirus-cases_latest.json** feed we're seeing:

```
FetchError: invalid json response body at https://c19downloads.azureedge.net/downloads/json/coronavirus-cases_latest.json reason: Unexpected token N in JSON at position 5628747)
```

**Comment by przemyslawpluta** [comment]
It appears that now the feed is not compressed either as **content-encoding**  header is missing and feed is around **8.4MB**

**Comment by przemyslawpluta** [comment]
Looks like feed contains **NaN** value which is not a valid JSON token and seems to be present in **dailyTotalLabConfirmedCasesRate**

**Comment by xenatisch** [comment]
@przemyslawpluta 

Please see issue #62 regarding the ongoing discussion on gzip.

With regards to the parsing issue, `NaN` is a value JSON value (see the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN) for details). It is supported in all modern parsers and browsers. 

What platform / language are you using to parse? 

We have two options:

1. We can replace `NaN` values with `null`
2. You can replace `NaN` values with `null`

The rationale behind using `NaN` is that the property type gets recognised as numeric, instead of unknown and numeric (e.g. `float64` instead of `object` in Python's Pandas). 

I'm open to changing it if there it's too annoying though, but I'd like to know what language (version, build, and platform) and parser are you using for the job.

**Comment by przemyslawpluta** [comment]
@xenatisch **NaN** is not a valid value in JSON spec https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON or https://en.wikipedia.org/wiki/JSON **null** in this case is preferable.

<img width="688" alt="json" src="https://user-images.githubusercontent.com/221250/82432432-f59a1600-9a87-11ea-85cc-4ceaa3e86372.png">

**Comment by xenatisch** [comment]
@przemyslawpluta Alright. That's fair enough. It'll cause a bit of headache in our data transmission to the database, but that's my problem.

This is only happening because yesterday's data is missing! 

I have now replaced `NaN` values in the latest dataset, and will change the ETL code to ensure that it is replaced automatically in future deployments.

**Comment by xenatisch** [comment]
Resolved in [the ETL](https://github.com/PublicHealthEngland/coronavirus-dashboard-pipeline-etl/commit/75008cd18f7a92c2bb2deb10f63c462605148ddd).

**Comment by przemyslawpluta** [comment]
Thanks and yes it was a surprise to us yesterday as well that there was no report in terms of how many people have been tested.

<img width="649" alt="people-tested" src="https://user-images.githubusercontent.com/221250/82445481-c7730100-9a9c-11ea-9db5-07c979564941.png">

**Comment by xenatisch** [comment]
@przemyslawpluta It was also indicated in the metedata of the JSON file, while also displayed underneath the figures on the website. 

It was a tech issue upstream on which PHE had no control... oh well, tech glitches happen.

Thanks for following up on this, and finding the docs for me to justify the changes. I / we appreciate your contribution.
