### ISSUE TITLE
Don't mix up patients in hospital days

### ISSUE THREAD

**Issue by acme** [publichealthengland/coronavirus-dashboard#197]
https://coronavirus-staging.data.gov.uk/about-data#patients-in-hospital says:

> Due to the way Northern Ireland report, the UK figure is calculated by taking the most recent day for Great Britain plus the previous day for Northern Ireland.

The data for different days should not be added up and shown on the same day.

In fact, as:

> National data may not be directly comparable as data about COVID-19 patients in hospitals are collected differently across nations.

... perhaps the chart should split out the nations.

**Comment by xenatisch** [comment]
@acme Thank you for getting in touch. This issue is unrelated to the development of the platform. 

I will forward your feedback to the relevant team, but may I suggest that you please get in touch via the email provided on the website so that your feedback will get processed and directed to the team through the appropriate channels. This will give them the opportunity to respond to your query / feedback if deemed necessary.
