### ISSUE TITLE
Invalid cache-control headers in v2

### ISSUE THREAD

**Issue by acme** [publichealthengland/coronavirus-dashboard#198]
https://coronavirus-staging.data.gov.uk/ loads some assets which have invalid `Cache-Control` response headers:

```
❯ curl -sI https://c19pubstaging.azureedge.net/assets/dispatch/website_timestamp | grep -i Cache-Control
cache-control: no-cache, max-age=0no-cache, max-age=0, stale-while-revalidate=300
❯ curl -sI https://c19pubstaging.azureedge.net/assets/structural_layouts/UKSummary.json | grep -i Cache-Control
cache-control: no-cache, max-age=0, stale-while-revalidate=300no-cache, max-age=0, stale-while-revalidate=300
```

Perhaps something along the way is concatenating to that header value rather than replacing it?

**Comment by xenatisch** [comment]
hmmm! That's bizarre and interesting. It's probably the CDN appending the heading instead of replacing its value. It'll look into it. 

Thanks for the heads up, @acme

**Comment by xenatisch** [comment]
Thanks again @acme - turns out I was right, it was the CDN appending instead of replacing. I correct the rule and it appears to have been resolved.

<img width="834" alt="Screenshot 2020-06-29 at 23 33 40" src="https://user-images.githubusercontent.com/13240654/86062761-504c6780-ba61-11ea-924e-f1ba137ef592.png">
