### ISSUE TITLE
Suggestion: show positive cases as % of tests

### ISSUE THREAD

**Issue by paulmaunders** [publichealthengland/coronavirus-dashboard#232]
The daily cases graph is helpful, but as we are testing much more now I think it would be useful to create an additional graph showing the % of positive test results each day.

Something like this:

<img width="591" alt="Screenshot 2020-09-01 at 09 31 53" src="https://user-images.githubusercontent.com/245434/91838914-23295a80-ec46-11ea-9646-64052aadbd83.png">

This will allow a more accurate comparison with the earlier stages of the pandemic.

If you are able to link cases to the test pilar in which they were found, and therefore create such a graph for each testing pilar it would be even more helpful as it would allow a like-for-like comparison.

**Comment by xenatisch** [comment]
@paulmaunders Thank you for getting in touch. I'm afraid this is not a development issue and is related to our data and contents teams. 

I will forward your comments, but I recommend that you get in touch via the email provided on the website so that your suggestions are directed to the relevant teams in case they wish to provide you with a response. 

@statsgeekclare @PHEgeorginaanderson, FYI.

**Comment by paulmaunders** [comment]
Thank you. I've sent an email.
