### ISSUE TITLE
Restore counts to the MSOA case data

### ISSUE THREAD

**Issue by rcatlord** [publichealthengland/coronavirus-dashboard#235]
The data files reporting the number of [confirmed cases of COVID-19 by Middle-layer Super Output Area](https://coronavirus.data.gov.uk/cases) are unhelpful or misleading. 

<img width="579" alt="cases_by_local_area" src="https://user-images.githubusercontent.com/12719575/92222571-21a2a100-ee97-11ea-9425-c7e964c05ed2.png">

- Case counts of less than 3 are shown as "0-2" in the Excel file rather than 0, 1, or 2. This is unhelpful because it is unclear whether zero, 1 or 2 cases of coronavirus were reported. 
- Case counts of less than 3 are shown as "-99" in the CSV file rather than 0, 1, or 2. This is misleading because "-99" is typically used to refer to a missing value.

Please can the case counts be disaggregated in the Excel file and numeric values be restored in the CSV file.

**Comment by xenatisch** [comment]
Thank you for getting in touch.

I'm afraid this is not a development issue and relates to our data and contents team. I will forward your message to them, but I recommend that you get in touch via the email provided on the website. The emails are shared with the relevant team and they will have the opportunity to respond if necessary. 

FYI @statsgeekclare / @PHEgeorginaanderson

**Comment by rcatlord** [comment]
Thanks @xenatisch. I submitted an issue because I was sure of a response. Also, the dashboard describes the format of the MSOA case data so it is relevant to the developers.

**Comment by xenatisch** [comment]
Not sure what you mean by "the dashboard describes the format of the MSOA case data". 

The development team provides the means to publish the data. On occasion, we also provide services to facilitate the conversion of formats and automated QAs. 

The values between 0-2 (inclusive) in MSOA and LSOA data have been removed to protect people's privacy and ensure that the data is not personally identifiable. Missing values were being interpreted by users as either missing or zero - both assumptions are incorrect. The -99 is therefore used so inform users that the specific value is neither zero nor missing, but excluded. 

Neither of the aforementioned decisions were made by the development team. We receive the Excel and CSV files on a daily basis, run it through a filter to ensure no unauthorised disclosure is made by accident, then use them to generate XML and JSON files and schedule them for publication at the designated time, which is currently 4pm. If the file is corrupt or if it doesn't get published when it should, then it is a problem for us to address. Anything else falls outside of our domain.  

Hope this helps.

**Comment by rcatlord** [comment]
Thanks. As per the screenshot, I only meant that the dashboard contains text that describes the format of the data available to download.

I'm not convinced that it is appropriate to use "-99" to indicate excluded data and values between 0 and 2. How about adopting:

-  '-' to indicate the case count is less than 3
- 0 to indicate zero cases
- NA to indicate that data are not available

**Comment by xenatisch** [comment]
I'm afraid it is not our decision to alter the presentation or the methodology. Whether or not "-99" is appropriate is, again, not a decision made by one individual. You are nonetheless more than welcome to express your opinion via the email provided on the website. I assure you that all suggestions and requests are reviewed and recorded by the relevant team and influence the decisions that make everyday.

> [...] the dashboard contains text that describes the format of the data available to download.

Again, the content of the website is dynamic. It is created by a different team - the content team. We as the development team are not responsible for they way in which they are presented. The content have their [own repository](https://github.com/publichealthengland/coronavirus-dashboard-layouts) as do the [metadata](https://github.com/publichealthengland/coronavirus-dashboard-metadata). Please note that the "issues" section of these repositories are not monitored and all relevant issues and queries are expected to be raised and handled via email. 

We as the development team are responsible for linking the content and the metadata to platform that we have created and provide technical advice where required. We are also responsible for the daily deployment of data, the API, the SDK services, and the infrastructure. 

> I'm not convinced that it is appropriate to use "-99" to indicate excluded data and values between 0 and 2. How about adopting:
> - '-' to indicate the case count is less than 3
> - 0 to indicate zero cases
> - NA to indicate that data are not available

As I mentioned in my previous message, all values that are smaller than 3 are indicated as "-99". The fact that zero is included in the filter is intentional and is to prevent the disclosure of identities. You might think that zero means that there is no case, so there is no identity to protect. Whilst that is correct, that subsequent change from zero to an alternative value - e.g. a "-" as you proposed - would indicate that at least one diagnosis has been confirmed, and that would risk revealing the identity of individuals when the dataset is presented at a granular level. 

Hope this helps.

**Comment by rcatlord** [comment]
If the case counts between 0 and 2 are suppressed for reasons of privacy then that's obviously fine. I still think the use of "-99" is confusing and inconsistent with the "0-2" used in the Excel spreadsheet. Perhaps, "-", "x" or even "0-2" would be better but let's leave that to the data and contents team.

**Comment by xenatisch** [comment]
> If the case counts between 0 and 2 are suppressed for reasons of privacy then that's obviously fine.

That is indeed the one and only reason. 

> I still think the use of "-99" is confusing and inconsistent with the "0-2" used in the Excel spreadsheet. Perhaps, "-", "x" or even "0-2" would be better but let's leave that to the data and contents team.

I think the point of using a numeric value is that it is both explicit and can be filtered out pretty quickly and easily. Non-numeric values - which include all of your recommended substitutes - require processes that are computationally more expensive, so it would be more difficult and time consuming to filter them out in both Excel and the programming languages that people use to analyse the data. In all likelihood, using non-numeric values for the amount of data we present in MSOA / LSOA datasets might actually crash Excel on older machines.

We used to leave them empty and that was fine, but then people were confusing them with zero / missing, which wasn't the case.

**Comment by rcatlord** [comment]
I really appreciate that you've considered both spreadsheet users and programmers in the choice of value to indicate suppressed data. The rationale is persuasive although the solution, perhaps inevitably, is still an accommodation. Thanks for your time.
