### ISSUE TITLE
Access to archive data

### ISSUE THREAD

**Issue by radka-j** [publichealthengland/coronavirus-dashboard#241]
**Is your feature request related to a problem? Please describe.**
We need  access to the archive data for case counts by LTLA (i.e., the data as reported on different dates). This used to be accessible here: https://coronavirus.data.gov.uk/archive but this was discontinued and we were told the API will make the archive available instead.

**Describe the solution you'd like**
We would like to be able to query by report date and specimen date.

**Additional context**
I opened an issue regarding this over a month ago [here](https://github.com/publichealthengland/coronavirus-dashboard-api-python-sdk/issues/3) and was told that this feature is on the development plan but I haven't had any updates since. What are the current plans and timeline for making the archive accessible again?

**Comment by james-nhsx** [comment]
Thank you for looking into this. Estimation of the lag in reporting is likely to become increasingly important for us (JBC)(https://www.bbc.co.uk/news/health-54191745). @xenatisch, looking at this repo and the previous one we can see how hard you're working- thank you for that. We're hoping that because the archive endpoint used to exist, it might not cause you too many issues to open up this endpoint again?

**Comment by theosanderson** [comment]
@radka-j @james-nhsx in case it's helpful in the short term I have recent data here by UTLA: https://github.com/theosanderson/covid_uk_data_timestamped/tree/master/utla_cases

**Comment by radka-j** [comment]
@theosanderson thank you for sharing these, we really appreciate it! This is definitely helpful while we wait to get access to the LTLA level data :)

**Comment by xenatisch** [comment]
Apologies for a very late response, and thank you @theosanderson for the solution you offered. 

Archives are now available from the [downloads](https://coronavirus.data.gov.uk/details/download) page.
