### ISSUE TITLE
Archive data UI allows selecting today's date when data for today has not yet been released

### ISSUE THREAD

**Issue by theosanderson** [publichealthengland/coronavirus-dashboard#264]
**Describe the bug**
If you go to Download Data prior to data release on a particular day, the default date in the Archive section (today's date) produces a URL that gives an unclear error, due to the lack of data.

Browser: Chrome on Windows and Android

**Comment by xenatisch** [comment]
This issue was being caused as a result of the release date for new data being updated before it had actually been QAed and released. The result was that the [API v2 software](https://github.com/publichealthengland/coronavirus-dashboard-api-v2) did not have sufficient permission to access new data, and so it failed. 

This was fixed a few weeks ago, so I would expect it to work properly now.
