### ISSUE TITLE
Nested Metrics

### ISSUE THREAD

**Issue by DanCookson** [publichealthengland/coronavirus-dashboard#352]
Hi
Further to our Twitter dialogue I'm just flagging that request for nested metric (demography) and other metric failed.  Separate requests work fine.
areaType=ltla&metric=newCasesBySpecimenDate&metric=newCasesBySpecimenDateAgeDemographics&format=csv

Thanks again
Dan

**Comment by xenatisch** [comment]
Thanks for reporting this. 

The issue here - which is in part related to the [APIv2 repository](https://github.com/publichealthengland/coronavirus-dashboard-api-v2-server) - is that nested metric have a different CSV structure, which can't really accommodate other metrics. 

This is therefore not a fixable issue, but it needs to be documented. For that reason, I have now changed the label of the issue to `Correction` + `documentation`. 

As a fix, I will be adding a line to the **Downloads** page to clarify the restriction.

**Comment by xenatisch** [comment]
@grobaan could you please look into adding a line of documentation - possibly as a note at the end of the "help text" for the `Metrics` field?
