### ISSUE TITLE
Credible intervals for data/expected data errors/data stability

### ISSUE THREAD

**Issue by timcoote** [PublicHealthEngland/coronavirus-dashboard#498]
This may well be the wrong location for this issue, but I cannot find anywhere else.

Access to these data is excellent. However, I'm struggling to find data quality measures. As a concrete example, I have seen the number of cases in an area change over time for a specific date many months after the data were originally captured. This may be expected, but it would be good to know.

A concrete example:
I queried the data after 4pm BST on 7th and 8th of October 2021. 
The data for 7th October included a  newCasesBySpecimenDate for 2020-11-03 for the LTLA of `Sevenoaks` of 26 the dat retrieved on 8th October had a value of 27.

Clearly the change in this example is small, but it does relate to records that are nearly a year old, potentially casting some doubt on the reliability of the data validation and extraction processes. Are there any expectations of the frequency/size of such errors and any work pinning down where the weaknesses in the data pipeline lie?

**Comment by statsgeekclare** [comment]
Hi Tim

A lot of what you were seeing here was related to how geographies are allocated to cases which has been updated with the move to episode-based reporting that happened at the end of January. The geography is now allocated to the first specimen in an episode rather than to the most recent. This should mean more stability. However, these are surveillance data that are refreshed every day so changes can and do occur.

There are also issues upstream from our processing if dates are incorrectly entered at labs for example.

I hope this is helpful. For future queries relating to the data rather than to the site itself you would get a faster response by emailing our enquiries inbox at coronavirus-tracker@phe.gov.uk.

Thanks
Clare
